from typing import Dict, List

# Canonical schema for legal KG entities and edges used by ingest/retrieval.
LEGAL_KG_SCHEMA: Dict[str, Dict[str, List[str]]] = {
    "nodes": {
        "LegalDocument": [
            "user_id",
            "doc_id",
            "filename",
            "page_count",
            "created_at",
            "updated_at",
        ],
        "LegalNode": [
            "user_id",
            "node_id",
            "doc_id",
            "node_type",
            "title",
            "text",
            "search_text",
            "section_tag",
            "section_path",
            "citations",
            "identifier",
            "page_start",
            "page_end",
            "depth",
            "order_index",
            "path",
            "parent_id",
            "created_at",
            "updated_at",
        ],
        "LegalAct": [
            "user_id",
            "name",
            "description",
            "source_url",
            "created_at",
            "updated_at",
        ],
        "LegalEvent": [
            "user_id",
            "event_id",
            "doc_id",
            "source_node_id",
            "subject",
            "action",
            "object",
            "event_time",
            "confidence",
            "created_at",
            "updated_at",
        ],
        "LegalParty": [
            "user_id",
            "name",
            "role",
            "created_at",
            "updated_at",
        ],
    },
    "relationships": {
        "HAS_ROOT": ["LegalDocument", "LegalNode"],
        "HAS_CHILD": ["LegalNode", "LegalNode"],
        "REFERENCES": ["LegalNode", "LegalNode|LegalAct"],
        "HAS_EVENT": ["LegalNode", "LegalEvent"],
        "INVOLVES": ["LegalEvent", "LegalParty"],
    },
}
